/*Copyright (c) 2018-2019 sqli.com All Rights Reserved.
 This software is the confidential and proprietary information of sqli.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with sqli.com*/
package ch.etg.application.exemple.etg.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import ch.etg.application.exemple.etg.EtgArticle;


/**
 * ServiceImpl object for domain model class EtgArticle.
 *
 * @see EtgArticle
 */
@Service("etg.EtgArticleService")
@Validated
public class EtgArticleServiceImpl implements EtgArticleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EtgArticleServiceImpl.class);


    @Autowired
    @Qualifier("etg.EtgArticleDao")
    private WMGenericDao<EtgArticle, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<EtgArticle, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "etgTransactionManager")
    @Override
	public EtgArticle create(EtgArticle etgArticle) {
        LOGGER.debug("Creating a new EtgArticle with information: {}", etgArticle);

        EtgArticle etgArticleCreated = this.wmGenericDao.create(etgArticle);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(etgArticleCreated);
    }

	@Transactional(readOnly = true, value = "etgTransactionManager")
	@Override
	public EtgArticle getById(Integer etgarticleId) throws EntityNotFoundException {
        LOGGER.debug("Finding EtgArticle by id: {}", etgarticleId);
        return this.wmGenericDao.findById(etgarticleId);
    }

    @Transactional(readOnly = true, value = "etgTransactionManager")
	@Override
	public EtgArticle findById(Integer etgarticleId) {
        LOGGER.debug("Finding EtgArticle by id: {}", etgarticleId);
        try {
            return this.wmGenericDao.findById(etgarticleId);
        } catch(EntityNotFoundException ex) {
            LOGGER.debug("No EtgArticle found with id: {}", etgarticleId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "etgTransactionManager")
    @Override
    public EtgArticle getByNumero(Integer numero) {
        Map<String, Object> numeroMap = new HashMap<>();
        numeroMap.put("numero", numero);

        LOGGER.debug("Finding EtgArticle by unique keys: {}", numeroMap);
        EtgArticle etgArticle = this.wmGenericDao.findByUniqueKey(numeroMap);

        if (etgArticle == null){
            LOGGER.debug("No EtgArticle found with given unique key values: {}", numeroMap);
            throw new EntityNotFoundException(String.valueOf(numeroMap));
        }

        return etgArticle;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "etgTransactionManager")
	@Override
	public EtgArticle update(EtgArticle etgArticle) throws EntityNotFoundException {
        LOGGER.debug("Updating EtgArticle with information: {}", etgArticle);

        this.wmGenericDao.update(etgArticle);
        this.wmGenericDao.refresh(etgArticle);

        return etgArticle;
    }

    @Transactional(value = "etgTransactionManager")
	@Override
	public EtgArticle delete(Integer etgarticleId) throws EntityNotFoundException {
        LOGGER.debug("Deleting EtgArticle with id: {}", etgarticleId);
        EtgArticle deleted = this.wmGenericDao.findById(etgarticleId);
        if (deleted == null) {
            LOGGER.debug("No EtgArticle found with id: {}", etgarticleId);
            throw new EntityNotFoundException(String.valueOf(etgarticleId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "etgTransactionManager")
	@Override
	public void delete(EtgArticle etgArticle) {
        LOGGER.debug("Deleting EtgArticle with {}", etgArticle);
        this.wmGenericDao.delete(etgArticle);
    }

	@Transactional(readOnly = true, value = "etgTransactionManager")
	@Override
	public Page<EtgArticle> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all EtgArticles");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "etgTransactionManager")
    @Override
    public Page<EtgArticle> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all EtgArticles");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "etgTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service etg for table EtgArticle to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "etgTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "etgTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

