/*Copyright (c) 2018-2019 sqli.com All Rights Reserved.
 This software is the confidential and proprietary information of sqli.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with sqli.com*/
package ch.etg.application.exemple.etg;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * EtgArticle generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ETG_ARTICLE`", uniqueConstraints = {
            @UniqueConstraint(name = "`IDX_ETG_ARTICLE_UNIQ_NUMERO`", columnNames = {"`NUMERO`"}),
            @UniqueConstraint(name = "`SYS_IDX_SYS_CT_10374_10379`", columnNames = {"`ID`"})})
@IdClass(EtgArticleId.class)
public class EtgArticle implements Serializable {

    private Integer id;
    private Integer numero;
    private String libelle;
    private BigDecimal prix;
    private List<EtgLigneCommande> etgLigneCommandes;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`NUMERO`", nullable = false, scale = 0, precision = 10)
    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    @Id
    @Column(name = "`LIBELLE`", nullable = false, length = 255)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Id
    @Column(name = "`PRIX`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getPrix() {
        return this.prix;
    }

    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }


    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "etgArticle")
    @Cascade({CascadeType.SAVE_UPDATE})
    public List<EtgLigneCommande> getEtgLigneCommandes() {
        return this.etgLigneCommandes;
    }

    public void setEtgLigneCommandes(List<EtgLigneCommande> etgLigneCommandes) {
        this.etgLigneCommandes = etgLigneCommandes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EtgArticle)) return false;
        final EtgArticle etgArticle = (EtgArticle) o;
        return Objects.equals(getId(), etgArticle.getId()) &&
                Objects.equals(getNumero(), etgArticle.getNumero()) &&
                Objects.equals(getLibelle(), etgArticle.getLibelle()) &&
                Objects.equals(getPrix(), etgArticle.getPrix());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getNumero(),
                getLibelle(),
                getPrix());
    }
}

