/*Copyright (c) 2018-2019 sqli.com All Rights Reserved.
 This software is the confidential and proprietary information of sqli.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with sqli.com*/
package ch.etg.application.exemple.etg;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * EtgCommande generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ETG_COMMANDE`", uniqueConstraints = {
            @UniqueConstraint(name = "`IDX_ETG_COMMANDE_UNIQ_NUMERO`", columnNames = {"`NUMERO`"}),
            @UniqueConstraint(name = "`SYS_IDX_SYS_CT_10366_10370`", columnNames = {"`ID`"})})
@IdClass(EtgCommandeId.class)
public class EtgCommande implements Serializable {

    private Integer id;
    private Integer numero;
    private String client;
    private Date dateCommande;
    private Boolean statut;
    private BigDecimal total;
    private List<EtgLigneCommande> etgLigneCommandes;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`NUMERO`", nullable = false, scale = 0, precision = 10)
    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    @Id
    @Column(name = "`CLIENT`", nullable = true, length = 255)
    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    @Id
    @Column(name = "`DATE_COMMANDE`", nullable = true)
    public Date getDateCommande() {
        return this.dateCommande;
    }

    public void setDateCommande(Date dateCommande) {
        this.dateCommande = dateCommande;
    }

    @Id
    @Column(name = "`STATUT`", nullable = true)
    public Boolean getStatut() {
        return this.statut;
    }

    public void setStatut(Boolean statut) {
        this.statut = statut;
    }

    @Id
    @Column(name = "`TOTAL`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }


    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "etgCommande")
    @Cascade({CascadeType.SAVE_UPDATE})
    public List<EtgLigneCommande> getEtgLigneCommandes() {
        return this.etgLigneCommandes;
    }

    public void setEtgLigneCommandes(List<EtgLigneCommande> etgLigneCommandes) {
        this.etgLigneCommandes = etgLigneCommandes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EtgCommande)) return false;
        final EtgCommande etgCommande = (EtgCommande) o;
        return Objects.equals(getId(), etgCommande.getId()) &&
                Objects.equals(getNumero(), etgCommande.getNumero()) &&
                Objects.equals(getClient(), etgCommande.getClient()) &&
                Objects.equals(getDateCommande(), etgCommande.getDateCommande()) &&
                Objects.equals(getStatut(), etgCommande.getStatut()) &&
                Objects.equals(getTotal(), etgCommande.getTotal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getNumero(),
                getClient(),
                getDateCommande(),
                getStatut(),
                getTotal());
    }
}

