/*Copyright (c) 2018-2019 sqli.com All Rights Reserved.
 This software is the confidential and proprietary information of sqli.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with sqli.com*/
package ch.etg.application.exemple.etg;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * EtgLigneCommande generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ETG_LIGNE_COMMANDE`", uniqueConstraints = {
            @UniqueConstraint(name = "`SYS_IDX_SYS_CT_10384_10390`", columnNames = {"`ID`"})})
@IdClass(EtgLigneCommandeId.class)
public class EtgLigneCommande implements Serializable {

    private Integer id;
    private Integer numero;
    private Integer commandeId;
    private Integer articleId;
    private Integer nombreArticle;
    private BigDecimal totalArticle;
    private BigDecimal prixArticle;
    private EtgArticle etgArticle;
    private EtgCommande etgCommande;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`NUMERO`", nullable = true, scale = 0, precision = 10)
    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    @Id
    @Column(name = "`COMMANDE_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getCommandeId() {
        return this.commandeId;
    }

    public void setCommandeId(Integer commandeId) {
        this.commandeId = commandeId;
    }

    @Id
    @Column(name = "`ARTICLE_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    @Id
    @Column(name = "`NOMBRE_ARTICLE`", nullable = false, scale = 0, precision = 10)
    public Integer getNombreArticle() {
        return this.nombreArticle;
    }

    public void setNombreArticle(Integer nombreArticle) {
        this.nombreArticle = nombreArticle;
    }

    @Id
    @Column(name = "`TOTAL_ARTICLE`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getTotalArticle() {
        return this.totalArticle;
    }

    public void setTotalArticle(BigDecimal totalArticle) {
        this.totalArticle = totalArticle;
    }

    @Id
    @Column(name = "`PRIX_ARTICLE`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getPrixArticle() {
        return this.prixArticle;
    }

    public void setPrixArticle(BigDecimal prixArticle) {
        this.prixArticle = prixArticle;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`ARTICLE_ID`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_ETG_LIGNE_COMMANDE_ARTICLE`"))
    @Fetch(FetchMode.JOIN)
    public EtgArticle getEtgArticle() {
        return this.etgArticle;
    }

    public void setEtgArticle(EtgArticle etgArticle) {
        if(etgArticle != null) {
            this.articleId = etgArticle.getId();
        }

        this.etgArticle = etgArticle;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`COMMANDE_ID`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_ETG_LIGNE_COMMANDE_COMMANDE`"))
    @Fetch(FetchMode.JOIN)
    public EtgCommande getEtgCommande() {
        return this.etgCommande;
    }

    public void setEtgCommande(EtgCommande etgCommande) {
        if(etgCommande != null) {
            this.commandeId = etgCommande.getId();
        }

        this.etgCommande = etgCommande;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EtgLigneCommande)) return false;
        final EtgLigneCommande etgLigneCommande = (EtgLigneCommande) o;
        return Objects.equals(getId(), etgLigneCommande.getId()) &&
                Objects.equals(getNumero(), etgLigneCommande.getNumero()) &&
                Objects.equals(getCommandeId(), etgLigneCommande.getCommandeId()) &&
                Objects.equals(getArticleId(), etgLigneCommande.getArticleId()) &&
                Objects.equals(getNombreArticle(), etgLigneCommande.getNombreArticle()) &&
                Objects.equals(getTotalArticle(), etgLigneCommande.getTotalArticle()) &&
                Objects.equals(getPrixArticle(), etgLigneCommande.getPrixArticle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getNumero(),
                getCommandeId(),
                getArticleId(),
                getNombreArticle(),
                getTotalArticle(),
                getPrixArticle());
    }
}

