/*Copyright (c) 2018-2019 sqli.com All Rights Reserved.
 This software is the confidential and proprietary information of sqli.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with sqli.com*/
package ch.etg.application.exemple.etgdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * LigneCommande generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`LIGNE_COMMANDE`", uniqueConstraints = {
            @UniqueConstraint(name = "`UK_LIGNE_COMMANDE_NUMERO`", columnNames = {"`NUMERO`"})})
public class LigneCommande implements Serializable {

    private Integer id;
    private int numero;
    private String libelle;
    private BigDecimal prix;
    private Integer commandeId;
    private Commande commande;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`NUMERO`", nullable = false, scale = 0, precision = 10)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "`LIBELLE`", nullable = false, length = 255)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Column(name = "`PRIX`", nullable = true, scale = 0, precision = 10)
    public BigDecimal getPrix() {
        return this.prix;
    }

    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

    @Column(name = "`COMMANDE_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getCommandeId() {
        return this.commandeId;
    }

    public void setCommandeId(Integer commandeId) {
        this.commandeId = commandeId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`COMMANDE_ID`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_LIGNE_COMMANDE_TO_COM0NpDF`"))
    @Fetch(FetchMode.JOIN)
    public Commande getCommande() {
        return this.commande;
    }

    public void setCommande(Commande commande) {
        if(commande != null) {
            this.commandeId = commande.getId();
        }

        this.commande = commande;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LigneCommande)) return false;
        final LigneCommande ligneCommande = (LigneCommande) o;
        return Objects.equals(getId(), ligneCommande.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

